production:
  periodic_notifier:
    class: TicketNotifierJob
    queue: background
    schedule: at 8am every day
  periodic_status_change:
    class: AutoCloseTicketsJob
    queue: background
    schedule: every 1 minute

development:
  periodic_notifier:
    class: TicketNotifierJob
    queue: background
    schedule: at 8am every day
  periodic_status_change:
    class: AutoCloseTicketsJob
    queue: background
    schedule: every 1 minute
